#!/bin/bash
#PBS -N fiorire_hpo_multinode
#PBS -o fiorire_hpo_multinode.log
#PBS -e fiorire_hpo_multinode.err
#PBS -q gpu
#PBS -k oe
#PBS -m e
#PBS -M roberto.morelli.ext@leonardocompany.com
#PBS -l select=2:ngpus=4:ncpus=16,walltime=72:00:00
#PBS -v num_nodes=2,num_gpus=4,num_cpus=16,config_file=conv_ae2D,num_samples=100,entity=robmorelli,wandb_key=56b6f7f0b13c4d89207e51c28ceb90c24201eab5,wandb=1,project_name=fiorire1_hpc_multinode_conv2D

##PBS -v num_nodes=2,num_gpus=4,num_cpus=16,config_file=,num_samples=100,wandb_key=56b6f7f0b13c4d89207e51c28ceb90c24201eab5,entity=robmorelli

module load proxy/proxy_20
bash /davinci-1/home/morellir/artificial_intelligence/repos/fiorire/launch_hpo.sh
