# Optimization
tune_config:
      #intermediate_dim: tune.choice([1, 2, 5, 10, 20])
      epochs: tune.choice([200])
      lr: tune.choice([0.0006, 0.0003, 0.001])
      batch_size: tune.choice([100, 500])
      seq_in_length: tune.choice([16])
      embedding_dim: tune.choice([10, 16, 20, 32, 40, 48])
      n_layers: tune.choice([1,2,3])
      n_cells: tune.choice([1,2])
      lr_patience: tune.choice([5, 10])
      scaler: tune.choice(['RobustScaler-0.05-0.95', 'StandardScaler'])  # other choices {StandardScaler: None}, None
      perc_overlap: tune.choice([0, 0.3, 0.7])

# Dataset
dataset:
  name: 'fiorire'
  data_path: './data/fiorire/sentinel/dataset_4s/all_2016-2018_clean_4s.pkl'
  perc_overlap: 0
  chunks_num: 10
  seq_in_length: 16
  seq_out_length: null
  train_val_split: 0.8
  shuffle_train: True #shuffle the idx of the train
  feats: ['RW1_motcurr', 'RW2_motcurr', 'RW3_motcurr', 'RW4_motcurr']   #['RW1_motcurr', 'RW2_motcurr', 'RW3_motcurr', 'RW4_motcurr',
                  # 'RW1_therm', 'RW2_therm', 'RW3_therm', 'RW4_therm',
                  #'RW1_speed', 'RW2_speed', 'RW3_speed', 'RW4_speed',
                  #'RW1_cmd_volt', 'RW2_cmd_volt', 'RW3_cmd_volt', 'RW4_cmd_volt']
  target: null    # null: the same input features are the target; all: all the variables of the dataframe are the target; list/str: specific value/s
  remove_target: False
  dataset_subset: 12000000
  scaler: 'RobustScaler-0.05-0.95'   # other coiches {StandarcScaler: None}, None
  save_dataloaders: False
  forecast: 1

# Model
model:
  name: 'lstm'

resources:
  gpu_trial: 1
  cpu_trial: 12

opt:
  fine_tuning: False
  tune_report: 'val_loss'
  k_fold_cv: 0
  metrics: ['train_loss', 'val_loss']
  order_by: 'val_loss'
  num_workers: 12
